import { Constants } from "@/types/database";

// Enum-based filter options (from database)
export const seniorityOptions = Constants.public.Enums.seniority_level;
export const companySizeOptions = Constants.public.Enums.company_size;
export const buyingInfluenceOptions = Constants.public.Enums.buying_influence_level;
export const ossActivityOptions = Constants.public.Enums.oss_activity;
export const projectStatusOptions = Constants.public.Enums.project_status;
export const evaluationStatusOptions = Constants.public.Enums.evaluation_status;

// Common role types for developers
export const roleTypeOptions = [
  "backend",
  "frontend",
  "full-stack",
  "mobile",
  "devops",
  "sre",
  "data-engineer",
  "data-scientist",
  "ml-engineer",
  "security",
  "qa",
  "platform",
  "embedded",
  "desktop",
  "game-dev",
];

// Common programming languages
export const languageOptions = [
  "typescript",
  "javascript",
  "python",
  "java",
  "go",
  "rust",
  "c++",
  "c#",
  "c",
  "ruby",
  "php",
  "swift",
  "kotlin",
  "scala",
  "elixir",
  "haskell",
  "clojure",
  "dart",
  "r",
  "lua",
  "perl",
  "objective-c",
  "zig",
  "ocaml",
];

// Common frameworks
export const frameworkOptions = [
  "react",
  "next.js",
  "vue",
  "nuxt",
  "angular",
  "svelte",
  "express",
  "fastapi",
  "django",
  "flask",
  "spring",
  "rails",
  "laravel",
  "nest.js",
  "remix",
  "astro",
  "gatsby",
  "fastify",
  "hono",
  "gin",
  "echo",
  "fiber",
  ".net",
  "phoenix",
  "htmx",
];

// Common databases
export const databaseOptions = [
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "sqlite",
  "elasticsearch",
  "dynamodb",
  "firebase",
  "supabase",
  "cassandra",
  "neo4j",
  "cockroachdb",
  "mariadb",
  "oracle",
  "mssql",
  "clickhouse",
  "timescaledb",
  "planetscale",
  "neon",
  "turso",
];

// Common cloud platforms
export const cloudPlatformOptions = [
  "aws",
  "gcp",
  "azure",
  "vercel",
  "cloudflare",
  "digital-ocean",
  "heroku",
  "fly.io",
  "railway",
  "render",
  "netlify",
  "linode",
  "hetzner",
];

// Common devops tools
export const devopsToolOptions = [
  "docker",
  "kubernetes",
  "terraform",
  "ansible",
  "pulumi",
  "helm",
  "vagrant",
  "packer",
  "consul",
  "vault",
  "prometheus",
  "grafana",
  "datadog",
  "new-relic",
  "sentry",
];

// Common CI/CD tools
export const cicdToolOptions = [
  "github-actions",
  "gitlab-ci",
  "jenkins",
  "circleci",
  "travis-ci",
  "buildkite",
  "argo-cd",
  "drone",
  "azure-devops",
  "bitbucket-pipelines",
  "teamcity",
];

// Common testing frameworks
export const testingFrameworkOptions = [
  "jest",
  "vitest",
  "pytest",
  "cypress",
  "playwright",
  "selenium",
  "mocha",
  "junit",
  "rspec",
  "testing-library",
  "storybook",
  "puppeteer",
  "k6",
  "locust",
  "postman",
];

// Common API experience
export const apiExperienceOptions = [
  "rest",
  "graphql",
  "grpc",
  "websockets",
  "soap",
  "trpc",
  "openapi",
  "protobuf",
  "webhooks",
  "server-sent-events",
];

// Common operating systems
export const operatingSystemOptions = [
  "macos",
  "linux",
  "windows",
  "ios",
  "android",
  "freebsd",
  "chromeos",
];

// Common industries
export const industryOptions = [
  "saas",
  "fintech",
  "healthtech",
  "e-commerce",
  "edtech",
  "devtools",
  "cybersecurity",
  "ai-ml",
  "gaming",
  "media",
  "logistics",
  "real-estate",
  "legal-tech",
  "hr-tech",
  "insurance",
  "telecom",
  "government",
  "nonprofit",
  "consulting",
  "crypto-web3",
];

// Common paid tools
export const paidToolOptions = [
  "github",
  "gitlab",
  "jira",
  "linear",
  "notion",
  "slack",
  "figma",
  "datadog",
  "pagerduty",
  "1password",
  "postman",
  "jetbrains",
  "vscode",
  "cursor",
  "vercel",
  "netlify",
  "aws",
  "gcp",
  "azure",
  "stripe",
  "twilio",
  "sendgrid",
  "sentry",
  "launchdarkly",
  "segment",
  "amplitude",
  "mixpanel",
  "contentful",
  "sanity",
  "algolia",
  "auth0",
  "okta",
];

// Countries (common developer locations, alphabetical)
export const countryOptions = [
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Bulgaria",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Kenya",
  "Latvia",
  "Lithuania",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Vietnam",
];

// Common timezones for developer profiles
export const timezoneOptions = [
  "America/New_York",
  "America/Chicago",
  "America/Denver",
  "America/Los_Angeles",
  "America/Anchorage",
  "Pacific/Honolulu",
  "America/Phoenix",
  "America/Toronto",
  "America/Vancouver",
  "America/Mexico_City",
  "America/Sao_Paulo",
  "America/Buenos_Aires",
  "America/Bogota",
  "America/Lima",
  "Europe/London",
  "Europe/Dublin",
  "Europe/Paris",
  "Europe/Berlin",
  "Europe/Amsterdam",
  "Europe/Madrid",
  "Europe/Rome",
  "Europe/Zurich",
  "Europe/Vienna",
  "Europe/Stockholm",
  "Europe/Oslo",
  "Europe/Copenhagen",
  "Europe/Helsinki",
  "Europe/Warsaw",
  "Europe/Prague",
  "Europe/Budapest",
  "Europe/Bucharest",
  "Europe/Athens",
  "Europe/Istanbul",
  "Europe/Moscow",
  "Europe/Lisbon",
  "Africa/Cairo",
  "Africa/Lagos",
  "Africa/Nairobi",
  "Africa/Johannesburg",
  "Africa/Casablanca",
  "Asia/Dubai",
  "Asia/Riyadh",
  "Asia/Karachi",
  "Asia/Kolkata",
  "Asia/Dhaka",
  "Asia/Bangkok",
  "Asia/Jakarta",
  "Asia/Singapore",
  "Asia/Hong_Kong",
  "Asia/Shanghai",
  "Asia/Taipei",
  "Asia/Seoul",
  "Asia/Tokyo",
  "Asia/Manila",
  "Australia/Sydney",
  "Australia/Melbourne",
  "Australia/Brisbane",
  "Australia/Perth",
  "Pacific/Auckland",
  "Pacific/Fiji",
];

// Known display overrides for acronyms and special casing
const labelOverrides: Record<string, string> = {
  "ai-ml": "AI/ML",
  "qa": "QA",
  "sre": "SRE",
  "ci/cd": "CI/CD",
  "devops": "DevOps",
  "graphql": "GraphQL",
  "grpc": "gRPC",
  "trpc": "tRPC",
  "rest": "REST",
  "sql": "SQL",
  "mssql": "MSSQL",
  "nosql": "NoSQL",
  "aws": "AWS",
  "gcp": "GCP",
  "api": "API",
  "oss": "OSS",
  "saas": "SaaS",
  "fintech": "FinTech",
  "healthtech": "HealthTech",
  "edtech": "EdTech",
  "devtools": "DevTools",
  "hr-tech": "HR Tech",
  "legal-tech": "Legal Tech",
  "crypto-web3": "Crypto/Web3",
  "e-commerce": "E-Commerce",
  "next.js": "Next.js",
  "nest.js": "Nest.js",
  "vue": "Vue",
  "nuxt": "Nuxt",
  ".net": ".NET",
  "htmx": "HTMX",
  "fly.io": "Fly.io",
  "postgresql": "PostgreSQL",
  "mysql": "MySQL",
  "mongodb": "MongoDB",
  "redis": "Redis",
  "sqlite": "SQLite",
  "elasticsearch": "Elasticsearch",
  "dynamodb": "DynamoDB",
  "firebase": "Firebase",
  "supabase": "Supabase",
  "neo4j": "Neo4j",
  "cockroachdb": "CockroachDB",
  "mariadb": "MariaDB",
  "clickhouse": "ClickHouse",
  "timescaledb": "TimescaleDB",
  "planetscale": "PlanetScale",
  "neon": "Neon",
  "turso": "Turso",
  "github-actions": "GitHub Actions",
  "gitlab-ci": "GitLab CI",
  "circleci": "CircleCI",
  "travis-ci": "Travis CI",
  "argo-cd": "Argo CD",
  "azure-devops": "Azure DevOps",
  "bitbucket-pipelines": "Bitbucket Pipelines",
  "teamcity": "TeamCity",
  "buildkite": "Buildkite",
  "docker": "Docker",
  "kubernetes": "Kubernetes",
  "terraform": "Terraform",
  "ansible": "Ansible",
  "pulumi": "Pulumi",
  "helm": "Helm",
  "prometheus": "Prometheus",
  "grafana": "Grafana",
  "datadog": "Datadog",
  "new-relic": "New Relic",
  "sentry": "Sentry",
  "jest": "Jest",
  "vitest": "Vitest",
  "pytest": "pytest",
  "cypress": "Cypress",
  "playwright": "Playwright",
  "selenium": "Selenium",
  "mocha": "Mocha",
  "junit": "JUnit",
  "rspec": "RSpec",
  "testing-library": "Testing Library",
  "storybook": "Storybook",
  "puppeteer": "Puppeteer",
  "k6": "k6",
  "locust": "Locust",
  "postman": "Postman",
  "websockets": "WebSockets",
  "soap": "SOAP",
  "openapi": "OpenAPI",
  "protobuf": "Protobuf",
  "webhooks": "Webhooks",
  "server-sent-events": "Server-Sent Events",
  "macos": "macOS",
  "linux": "Linux",
  "windows": "Windows",
  "ios": "iOS",
  "android": "Android",
  "freebsd": "FreeBSD",
  "chromeos": "ChromeOS",
  "digital-ocean": "Digital Ocean",
  "heroku": "Heroku",
  "railway": "Railway",
  "render": "Render",
  "netlify": "Netlify",
  "cloudflare": "Cloudflare",
  "vercel": "Vercel",
  "hetzner": "Hetzner",
  "linode": "Linode",
  "github": "GitHub",
  "gitlab": "GitLab",
  "jira": "Jira",
  "linear": "Linear",
  "notion": "Notion",
  "slack": "Slack",
  "figma": "Figma",
  "pagerduty": "PagerDuty",
  "1password": "1Password",
  "jetbrains": "JetBrains",
  "vscode": "VS Code",
  "cursor": "Cursor",
  "stripe": "Stripe",
  "twilio": "Twilio",
  "sendgrid": "SendGrid",
  "launchdarkly": "LaunchDarkly",
  "segment": "Segment",
  "amplitude": "Amplitude",
  "mixpanel": "Mixpanel",
  "contentful": "Contentful",
  "sanity": "Sanity",
  "algolia": "Algolia",
  "auth0": "Auth0",
  "okta": "Okta",
  "oracle": "Oracle",
  "cassandra": "Cassandra",
  "vp_plus": "VP+",
  "early_career": "Early Career",
  "leadership": "Leadership",
  "individual_contributor": "Individual Contributor",
  "team_influencer": "Team Influencer",
  "decision_maker": "Decision Maker",
  "budget_holder": "Budget Holder",
  "ml-engineer": "ML Engineer",
  "data-engineer": "Data Engineer",
  "data-scientist": "Data Scientist",
  "full-stack": "Full-Stack",
  "game-dev": "Game Dev",
  "backend": "Backend",
  "frontend": "Frontend",
  "mobile": "Mobile",
  "security": "Security",
  "platform": "Platform",
  "embedded": "Embedded",
  "desktop": "Desktop",
  "typescript": "TypeScript",
  "javascript": "JavaScript",
  "python": "Python",
  "java": "Java",
  "go": "Go",
  "rust": "Rust",
  "c++": "C++",
  "c#": "C#",
  "c": "C",
  "ruby": "Ruby",
  "php": "PHP",
  "swift": "Swift",
  "kotlin": "Kotlin",
  "scala": "Scala",
  "elixir": "Elixir",
  "haskell": "Haskell",
  "clojure": "Clojure",
  "dart": "Dart",
  "r": "R",
  "lua": "Lua",
  "perl": "Perl",
  "objective-c": "Objective-C",
  "zig": "Zig",
  "ocaml": "OCaml",
  "react": "React",
  "angular": "Angular",
  "svelte": "Svelte",
  "express": "Express",
  "fastapi": "FastAPI",
  "django": "Django",
  "flask": "Flask",
  "spring": "Spring",
  "rails": "Rails",
  "laravel": "Laravel",
  "remix": "Remix",
  "astro": "Astro",
  "gatsby": "Gatsby",
  "fastify": "Fastify",
  "hono": "Hono",
  "gin": "Gin",
  "echo": "Echo",
  "fiber": "Fiber",
  "phoenix": "Phoenix",
};

// Label formatters for display
export function formatEnumLabel(value: string): string {
  const lower = value.toLowerCase();
  if (labelOverrides[lower]) return labelOverrides[lower];
  return value
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function formatFilterLabel(key: string): string {
  const labels: Record<string, string> = {
    role_types: "Role Types",
    seniority: "Seniority",
    min_experience: "Min Experience",
    max_experience: "Max Experience",
    languages: "Languages",
    frameworks: "Frameworks",
    databases: "Databases",
    cloud_platforms: "Cloud Platforms",
    devops_tools: "DevOps Tools",
    cicd_tools: "CI/CD Tools",
    testing_frameworks: "Testing Frameworks",
    api_experience: "API Experience",
    operating_systems: "Operating Systems",
    industries: "Industries",
    company_size: "Company Size",
    buying_influence: "Buying Influence",
    paid_tools: "Paid Tools",
    open_source_activity: "Open Source",
    is_available: "Availability",
  };
  return labels[key] ?? key;
}
